

procedure lng_eng;
begin
   str_MMap              := 'MAP';
   str_MPlayers          := 'PLAYERS';
   str_MObjectives       := 'OBJECTIVES';
   str_menu_s1[ms1_sett] := 'SETTINGS';
   str_menu_s1[ms1_svld] := 'SAVE/LOAD';
   str_menu_s1[ms1_reps] := 'REPLAYS';
   str_menu_s2[ms2_camp] := 'CAMPAIGNS';
   str_menu_s2[ms2_scir] := 'SKIRMISH';
   str_menu_s2[ms2_mult] := 'MULTIPLAYER';
   str_reset[false]      := 'START';
   str_reset[true ]      := 'RESET';
   str_exit[false]       := 'EXIT';
   str_exit[true]        := 'BACK';
   str_m_liq             := 'Lakes: ';
   str_m_siz             := 'Size: ';
   str_m_obs             := 'Obstacles: x';
   str_map               := 'Map';
   str_players           := 'Players';
   str_mrandom           := 'Random map';
   str_sound             := 'SOUND VOLUME';
   str_musicvol          := 'Music';
   str_soundvol          := 'Sound';
   str_game              := 'GAME';
   str_scrollspd         := 'Scroll speed';
   str_mousescrl         := 'Mouse scroll:';
   str_fullscreen        := 'Windowed:';
   str_plname            := 'Player name';
   str_lng[true]         := 'RUS';
   str_lng[false]        := 'ENG';
   str_maction           := 'Right click';
   str_maction2[true ]   := #18+'Move'+#25;
   str_maction2[false]   := #17+'Move'+#25+'+'+#17+'attack'+#25;
   str_race[r_random]    := 'random';
   str_race[r_hell  ]    := #16+'HELL'+#25;
   str_race[r_uac   ]    := #18+'UAC'+#25;
   str_win               := 'VICTORY!';
   str_lose              := 'DEFEAT!';
   str_pause             := 'Pause';
   str_gsaved            := 'Game saved';
   str_repend            := 'Replay ended!';
   str_save              := 'Save';
   str_load              := 'Load';
   str_delete            := 'Delete';
   str_svld_errors[1]    := 'File not'+#13+'exists!';
   str_svld_errors[2]    := 'Can`t open'+#13+'file!';
   str_svld_errors[3]    := 'Wrong file'+#13+'size!';
   str_svld_errors[4]    := 'Wrong version!';
   str_time              := 'Time: ';
   str_menu              := 'Menu';
   str_player_def        := ' was terminated!';
   str_inv_time          := 'Wave #';
   str_inv_ml            := 'Monsters: ';
   str_play              := 'Play';
   str_replay            := 'RECORD';
   str_cmpdif            := 'Difficulty: ';
   str_waitsv            := 'Awaiting server...';
   str_goptions          := 'GAME OPTIONS';
   str_server            := 'SERVER';
   str_client            := 'CLIENT';
   str_chat              := 'CHAT';
   str_gaddon            := 'Game:';
   str_randoms           := 'Random skirmish';
   str_apply             := 'apply';
   str_plout             := ' left the game';

   str_loss              := 'Loss condition:';
   str_losst[0]          := 'no army';
   str_losst[1]          := 'no builders';
   str_losst[2]          := 'no energy';

   str_starta            := 'Starting base:';
   str_startat[0]        := '1 '+#19+'builder'+#25;
   str_startat[1]        := '1 '+#19+'builder'+#25+'+ 1 '+#18+'gen.'+#25;
   str_startat[2]        := '1 '+#19+'builder'+#25+'+ 2 '+#18+'gen.'+#25;
   str_startat[3]        := '1 '+#19+'b.'+#25+'+ 2 '+#18+'gen.'+#25+'+ 2 '+#17+'b.'+#25;

   str_onebase           := 'One builder:';

   str_pnua[0]           := #19+'smallest'+#25+'/'+#15+'worst' +#25;
   str_pnua[1]           := #18+'small'   +#25+'/'+#16+'poor'  +#25;
   str_pnua[2]           := #17+'medium'  +#25+'/'+#17+'medium'+#25;
   str_pnua[3]           := #16+'large'   +#25+'/'+#18+'good'  +#25;
   str_pnua[4]           := #15+'largest' +#25+'/'+#19+'best'  +#25;

   str_npnua[0]          := #15+'lowest' +#25;
   str_npnua[1]          := #16+'low'    +#25;
   str_npnua[2]          := #17+'average'+#25;
   str_npnua[3]          := #18+'high'   +#25;
   str_npnua[4]          := #19+'highest'+#25;

   str_cmpd[0]           := #19+'I`m too young to die'+#25;
   str_cmpd[1]           := #18+'Hey, not too rough'+#25;
   str_cmpd[2]           := #17+'Hurt me plenty'+#25;
   str_cmpd[3]           := #16+'Ultra-Violence'+#25;
   str_cmpd[4]           := #15+'Nightmare!'+#25;

   str_gmodet            := 'Game mode:';
   str_gmode[0]          := 'Skirmish';
   str_gmode[1]          := 'Two fortress';
   str_gmode[2]          := 'Capturing points';
   str_gmode[3]          := 'Invasion';
   str_gmode[4]          := 'Assault';
   str_addon[false]      := #16+'UDOOM'+#25;
   str_addon[true ]      := #18+'DOOM 2'+#25;

   str_team              := 'Team:';
   str_srace             := 'Race:';
   str_ready             := 'Ready: ';
   str_udpport           := 'UDP port:';
   str_svup[false]       := 'Start server';
   str_svup[true ]       := 'Stop server';
   str_connect[false]    := 'Connect';
   str_connect[true ]    := 'Disconnect';
   str_pnu               := 'File size/quality: ';
   str_npnu              := 'Units update rate: ';
   str_connecting        := 'Connecting...';
   str_sver              := 'Wrong version!';
   str_sfull             := 'Server full!';
   str_sgst              := 'Game started!';

   str_hint_t[0]         := 'Buildings and Units';
   str_hint_t[1]         := 'Research';
   str_hint_t[2]         := 'Replays';

   str_hint_m[0]         := 'Menu ('          +#18+'Esc'+#25+')';
   str_hint_m[2]         := 'Pause ('         +#18+'Pause/Break'+#25+')';

   with _ulst[UID_HKeep     ] do str_hint[0,r_hell,0 ] := 'Hell Keep ('     +#18+'Q'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Builds base.';
   with _ulst[UID_HGate     ] do str_hint[0,r_hell,1 ] := 'Hell Gate ('     +#18+'W'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Summon units.';
   with _ulst[UID_HSymbol   ] do str_hint[0,r_hell,2 ] := 'Hell Symbol ('   +#18+'E'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Adds energy.';
   with _ulst[UID_HPools    ] do str_hint[0,r_hell,3 ] := 'Hell Pools ('    +#18+'A'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Research upgrades.';
   with _ulst[UID_HTower    ] do str_hint[0,r_hell,4 ] := 'Hell Tower ('    +#18+'S'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Defense structure.';
   with _ulst[UID_HTeleport ] do str_hint[0,r_hell,5 ] := 'Hell Teleport (' +#18+'D'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Teleporting units to any point.';
   with _ulst[UID_HMonastery] do str_hint[0,r_hell,6 ] := 'Hell Monastery ('+#18+'Z'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Upgrade units. '+#11+#17+'Requirements:'+#25+' Hell Pools';
   with _ulst[UID_HTotem    ] do str_hint[0,r_hell,7 ] := 'Hell Totem ('    +#18+'X'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Advanced defense structure. '+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   with _ulst[UID_HAltar    ] do str_hint[0,r_hell,8 ] := 'Hell Altar ('    +#18+'C'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Reapir buildings and cast "Hell power" on units.'+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[0,r_hell,9 ] := 'Lost Soul ('     +#18+'R'+#25+') ['+#19+b2s(_ulst[UID_LostSoul   ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,10] := 'Imp ('           +#18+'T'+#25+') ['+#19+b2s(_ulst[UID_Imp        ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,11] := 'Demon ('         +#18+'Y'+#25+') ['+#19+b2s(_ulst[UID_Demon      ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,12] := 'Cacodemon ('     +#18+'F'+#25+') ['+#19+b2s(_ulst[UID_Cacodemon  ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,13] := 'Baron of Hell / Hell Knight ('
                                              +#18+'G'+#25+') ['+#19+b2s(_ulst[UID_Baron      ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,14] := 'Cyberdemon ('    +#18+'H'+#25+') ['+#19+b2s(_ulst[UID_Cyberdemon ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,15] := 'Mastermind ('    +#18+'V'+#25+') ['+#19+b2s(_ulst[UID_Mastermind ].trt div vid_fps)+#25+']';
   str_hint[0,r_hell,16] := 'Pain Elemental ('+#18+'B'+#25+') ['+#19+b2s(_ulst[UID_Pain       ].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[0,r_hell,17] := 'Revenant ('      +#18+'N'+#25+') ['+#19+b2s(_ulst[UID_Revenant   ].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[0,r_hell,18] := 'Mancubus ('      +#18+'U'+#25+') ['+#19+b2s(_ulst[UID_Mancubus   ].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[0,r_hell,19] := 'Arachnotron ('   +#18+'I'+#25+') ['+#19+b2s(_ulst[UID_Arachnotron].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[0,r_hell,20] := 'ArchVile ('      +#18+'O'+#25+') ['+#19+b2s(_ulst[UID_ArchVile   ].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';

   str_hint[1,r_hell,upgr_attack ] := 'Range attack upgrade ('       +#18+'Q'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_attack  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_attack ])+#25+#11+'Increase damage of distance attacks.';
   str_hint[1,r_hell,upgr_armor  ] := 'Unit armor upgrade ('         +#18+'W'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_armor   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_armor  ])+#25+#11+'Increase armor of units.';
   str_hint[1,r_hell,upgr_build  ] := 'Buildinds armor upgrade ('    +#18+'E'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_build   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_build  ])+#25+#11+'Increase armor of buildings.';
   str_hint[1,r_hell,upgr_melee  ] := 'Melee attack upgrade ('       +#18+'A'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_melee   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_melee  ])+#25+#11+'Increase damage of melee attacks.';
   str_hint[1,r_hell,upgr_regen  ] := 'Regeneration ('               +#18+'S'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_regen   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_regen  ])+#25+#11+'Units will slowly regenerate their health.';
   str_hint[1,r_hell,upgr_paina  ] := 'Decay aura ('                 +#18+'D'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_paina   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_paina  ])+#25+#11+'Hell Keep will damage all enemies around.';
   str_hint[1,r_hell,upgr_vision ] := 'Hell vision ('                +#18+'Z'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_vision  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_vision ])+#25+#11+'Cyberdemon, Mastermind and Hell Altar becomes detectors.';
   str_hint[1,r_hell,upgr_pains  ] := 'Pain threshold ('             +#18+'X'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_pains   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_pains  ])+#25+#11+'Decrease "pain state" chance.';
   str_hint[1,r_hell,upgr_5bld   ] := 'Teleport upgrade ('           +#18+'C'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_5bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_5bld   ])+#25+#11+'Decrease reload time of teleport.';
   str_hint[1,r_hell,upgr_mainm  ] := 'Hell Keep teleportaion ('     +#18+'R'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_mainm   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_mainm  ])+#25+#11+'Hell keep can teleport to any point.';
   str_hint[1,r_hell,upgr_towers ] := 'Tower range upgrade ('        +#18+'T'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_towers  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_towers ])+#25+#11+'Increased attack range of defensive structures.';
   str_hint[1,r_hell,upgr_6bld   ] := 'Soul collector ('             +#18+'Y'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_6bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_6bld   ])+#25+#11+'Hell Monastery will be able to collect souls to upgrade units.';
   str_hint[1,r_hell,upgr_2tier  ] := 'Ancient evil ('               +#18+'F'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_2tier   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_2tier  ])+#25+#11+'Tier 2 buildings, units and upgrades.';
   str_hint[1,r_hell,upgr_mainr  ] := 'Hell keep range upgrade ('    +#18+'G'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_mainr   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_mainr  ])+#25+#11+'Increased range of view Hell Keep.'             +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_revtele] := 'Reverse teleport ('           +#18+'H'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_revtele ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_revtele])+#25+#11+'Units can teleport back to Hell Teleport.'      +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_revmis ] := 'Revenant missile upgrade ('   +#18+'V'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_revmis  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_revmis ])+#25+#11+'Increase attack range, missiles become homing.' +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_hpower ] := 'Hell power ('                 +#18+'N'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_hpower  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_hpower ])+#25+#11+'Hell altar ability upgrade.'                    +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_hsymbol] := 'Hell Symbol upgrade ('        +#18+'B'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_hsymbol ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_hsymbol])+#25+#11+'Increase Hell Symbol`s energy.'                 +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_bldrep ] := 'Building restoration ('       +#18+'U'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_bldrep  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_bldrep ])+#25+#11+'Hell altar ability.'                            +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_6bld2  ] := 'Soul storage ('               +#18+'I'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_6bld2   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_6bld2  ])+#25+#11+'Hell Monastery can storage more souls.'         +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_mainonr] := 'Loose teleportation ('        +#18+'O'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_mainonr ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_mainonr])+#25+#11+'Hell Keep can teleport to anywhere.'            +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_b478tel] := 'Symbols, Towers and Altars teleporting ('+#18+'J'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_b478tel ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_b478tel])+#25+#11+'Hell Symbols, Towers, Totems and Altars can teleport to short distance.'+#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';
   str_hint[1,r_hell,upgr_hinvuln] := 'Temporary Invulnerability ('  +#18+'K'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_hinvuln ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_hinvuln])+#25+#11+'All hell units become invulnerable for 15 seconds.'          +#11+#17+'Requirements:'+#25+' Hell Monastery, "Ancient evil" research.';


   with _ulst[UID_UCommandCenter ] do str_hint[0,r_uac ,0 ] := 'UAC Command Center (' +#18+'Q'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Builds base.';
   with _ulst[UID_UMilitaryUnit  ] do str_hint[0,r_uac ,1 ] := 'UAC Military unit ('  +#18+'W'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Traing units.';
   with _ulst[UID_UGenerator     ] do str_hint[0,r_uac ,2 ] := 'UAC Generator ('      +#18+'E'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Adds energy.';
   with _ulst[UID_UWeaponFactory ] do str_hint[0,r_uac ,3 ] := 'UAC Weapon Factory (' +#18+'A'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Research upgrades.';
   with _ulst[UID_UTurret        ] do str_hint[0,r_uac ,4 ] := 'UAC Turret ('         +#18+'S'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Defense structure.';
   with _ulst[UID_URadar         ] do str_hint[0,r_uac ,5 ] := 'UAC Radar ('          +#18+'D'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Reveal map.';
   with _ulst[UID_UVehicleFactory] do str_hint[0,r_uac ,6 ] := 'UAC Tech Center ('    +#18+'Z'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Upgrade units. '                  +#11+#17+'Requirements:'+#25+' Weapon Factory';
   with _ulst[UID_URTurret       ] do str_hint[0,r_uac ,7 ] := 'UAC Rocket turret ('  +#18+'X'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Advanced defense structure. '     +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   with _ulst[UID_URocketL       ] do str_hint[0,r_uac ,8 ] := 'UAC Rocket Launcher Station ('+#18+'C'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Provide a missile strike. Missile strike requires "Missile strike" research.'+#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[0,r_uac ,9 ] := 'Engineer ('           +#18+'R'+#25+') ['+#19+b2s(_ulst[UID_Engineer  ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,10] := 'Medic ('              +#18+'T'+#25+') ['+#19+b2s(_ulst[UID_Medic     ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,11] := 'Sergant ('            +#18+'Y'+#25+') ['+#19+b2s(_ulst[UID_Sergant   ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,12] := 'Commando ('           +#18+'F'+#25+') ['+#19+b2s(_ulst[UID_Commando  ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,13] := 'Bomber ('             +#18+'G'+#25+') ['+#19+b2s(_ulst[UID_Bomber    ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,14] := 'Major ('              +#18+'H'+#25+') ['+#19+b2s(_ulst[UID_Major     ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,15] := 'BFG Marine ('         +#18+'V'+#25+') ['+#19+b2s(_ulst[UID_BFG       ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,16] := 'Air APC ('            +#18+'B'+#25+') ['+#19+b2s(_ulst[UID_FAPC      ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,17] := 'Ground APC ('         +#18+'N'+#25+') ['+#19+b2s(_ulst[UID_APC       ].trt div vid_fps)+#25+']';
   str_hint[0,r_uac ,18] := 'UAC Terminator ('     +#18+'U'+#25+') ['+#19+b2s(_ulst[UID_Terminator].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[0,r_uac ,19] := 'UAC Tank ('           +#18+'I'+#25+') ['+#19+b2s(_ulst[UID_Tank      ].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[0,r_uac ,20] := 'UAC Fighter ('        +#18+'O'+#25+') ['+#19+b2s(_ulst[UID_Flyer     ].trt div vid_fps)+#25+']'+#11+#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';

   str_hint[1,r_uac ,upgr_attack ] := 'Range attack upgrade ('   +#18+'Q'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_attack  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_attack ])+#25+#11+'Increase damage of distance attacks.';
   str_hint[1,r_uac ,upgr_armor  ] := 'Infantry armor upgrade (' +#18+'W'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_armor   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_armor  ])+#25+#11+'Increase armor of infantry.';
   str_hint[1,r_uac ,upgr_build  ] := 'Buildinds armor upgrade ('+#18+'E'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_build   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_build  ])+#25+#11+'Increase armor of buildings.';
   str_hint[1,r_uac ,upgr_melee  ] := 'Repair and healing ('     +#18+'A'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_melee   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_melee  ])+#25+#11+'Increase the efficiency of repair/healing by an Engineer/Medic.';
   str_hint[1,r_uac ,upgr_mspeed ] := 'Lightweight armor ('      +#18+'S'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mspeed  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mspeed ])+#25+#11+'Increase infantry move speed.';
   str_hint[1,r_uac ,upgr_shield ] := 'Plasma shields ('         +#18+'D'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_shield  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_shield ])+#25+#11+'All buildings and mechs get plasma shields.';
   str_hint[1,r_uac ,upgr_vision ] := 'Detector device ('        +#18+'Z'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_vision  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_vision ])+#25+#11+'Radar and mines becomes detectors.';
   str_hint[1,r_uac ,upgr_invis  ] := 'Stealth troopers ('       +#18+'X'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_invis   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_invis  ])+#25+#11+'Infantry becomes invisible.';
   str_hint[1,r_uac ,upgr_5bld   ] := 'Radar upgrade ('          +#18+'C'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_5bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_5bld   ])+#25+#11+'Increase radar scouting time and radius.';
   str_hint[1,r_uac ,upgr_mainm  ] := 'Command Center flight ('  +#18+'R'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mainm   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mainm  ])+#25+#11+'Command Center will be able to fly.';
   str_hint[1,r_uac ,upgr_towers ] := 'Turrets range upgrade ('  +#18+'T'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_towers  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_towers ])+#25+#11+'Increased attack range of defensive structures.';
   str_hint[1,r_uac ,upgr_6bld   ] := 'Advanced armory ('        +#18+'Y'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_6bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_6bld   ])+#25+#11+'Tech Center will be able to upgrade units.';
   str_hint[1,r_uac ,upgr_2tier  ] := 'High technologies ('      +#18+'F'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_2tier   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_2tier  ])+#25+#11+'Tier 2 buildings, units and upgrades.';
   str_hint[1,r_uac ,upgr_mainr  ] := 'Command Center range ('   +#18+'G'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mainr   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mainr  ])+#25+#11+'Increased range of view Command Center.'        +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_blizz  ] := 'Missile strike ('         +#18+'H'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_blizz   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_blizz  ])+#25+#11+'Missile strike for Rocket Launcher Station.'    +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_mechspd] := 'Advanced engines ('       +#18+'V'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mechspd ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mechspd])+#25+#11+'Increase mechs move speed.'                     +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_mecharm] := 'Mech armor upgrade ('     +#18+'B'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mecharm ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mecharm])+#25+#11+'Increase mechs armor.'                          +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_ucomatt] := 'BFG turret ('             +#18+'N'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_ucomatt ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_ucomatt])+#25+#11+'Command Center will be able to attack.'         +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_minesen] := 'Mine-sensor ('            +#18+'U'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_minesen ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_minesen])+#25+#11+'Mine ability.'                                  +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_6bld2  ] := 'Fast rearmament ('        +#18+'I'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_6bld2   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_6bld2  ])+#25+#11+'Tech Center upgrade units faster.'              +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_mainonr] := 'Loose placement ('        +#18+'O'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mainonr ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mainonr])+#25+#11+'Command center will be able to land anywhere.'  +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_addtur ] := 'Additional turret ('      +#18+'J'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_addtur  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_addtur ])+#25+#11+'Additional weapon for UAC Turret.'              +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';
   str_hint[1,r_uac ,upgr_apctur ] := 'Turret for transport ('   +#18+'K'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_apctur  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_apctur ])+#25+#11+'Turret for APC.'                                +#11+#17+'Requirements:'+#25+' Tech Center, "High technologies" research.';


   str_hint[2,r_hell,0 ] := 'Faster game speed ('+#18+'Q'+#25+')';
   str_hint[2,r_hell,1 ] := 'Left click: skip 2 seconds ('+#18+'W'+#25+')'+#11+'Right click: skip 10 seconds ('+#18+'Ctrl'+#25+'+'+#18+'W'+#25+')';
   str_hint[2,r_hell,2 ] := 'List of game messages ('+#18+'E'+#25+')';
   str_hint[2,r_hell,3 ] := 'Fog of war ('+#18+'A'+#25+')';
   str_hint[2,r_hell,6 ] := 'All players ('+#18+'Z'+#25+')';
   str_hint[2,r_hell,7 ] := 'Red player [#1] ('+#18+'X'+#25+')';
   str_hint[2,r_hell,8 ] := 'Yellow player [#2] ('+#18+'C'+#25+')';
   str_hint[2,r_hell,9 ] := 'Green player [#3] ('+#18+'R'+#25+')';
   str_hint[2,r_hell,10] := 'Blue player [#4] ('+#18+'T'+#25+')';
   str_hint[2,r_uac ,0 ] := str_hint[2,r_hell,0 ];
   str_hint[2,r_uac ,1 ] := str_hint[2,r_hell,1 ];
   str_hint[2,r_uac ,2 ] := str_hint[2,r_hell,2 ];
   str_hint[2,r_uac ,3 ] := str_hint[2,r_hell,3 ];
   str_hint[2,r_uac ,6 ] := str_hint[2,r_hell,6 ];
   str_hint[2,r_uac ,7 ] := str_hint[2,r_hell,7 ];
   str_hint[2,r_uac ,8 ] := str_hint[2,r_hell,8 ];
   str_hint[2,r_uac ,9 ] := str_hint[2,r_hell,9 ];
   str_hint[2,r_uac ,10] := str_hint[2,r_hell,10];

   str_hint[0,r_uac ,25] := 'Mines';
   str_hint[1,r_uac ,25] := str_hint[0,r_uac ,25];
   str_hint[0,r_hell,25] := 'Zombie ('+#18+'M'+#25+')';
   str_hint[1,r_hell,25] := str_hint[0,r_hell,25];

   str_hint[0,r_uac ,21] := 'Action ('        +#18+'Ctrl'+#25+'+'+#18+'Space'+#25+')';
   str_hint[0,r_uac ,22] := 'Destroy ('       +#18+'Delete'+#25+')';
   str_hint[0,r_uac ,23] := 'Cancle ('        +#18+'Space'+#25+')';
   str_hint[1,r_uac ,24] := 'Menu ('          +#18+'Esc'+#25+')';
   str_hint[0,r_hell,21] := str_hint[0,r_uac ,21];
   str_hint[0,r_hell,22] := str_hint[0,r_uac ,22];
   str_hint[0,r_hell,23] := str_hint[0,r_uac ,23];
   str_hint[0,r_hell,24] := str_hint[0,r_uac ,24];
   str_hint[1,r_hell,24] := str_hint[1,r_uac ,24];

   str_camp_t[0]         := 'Hell #1: Phobos invasion';
   str_camp_t[1]         := 'Hell #2: Military base';
   str_camp_t[2]         := 'Hell #3: Deimos invasion';
   str_camp_t[3]         := 'Hell #4: Pentagram of Death';
   str_camp_t[4]         := 'Hell #7: Quarry';
   str_camp_t[5]         := 'Hell #8: Hell on Mars';
   str_camp_t[6]         := 'Hell #5: Hell on Earth';
   str_camp_t[7]         := 'Hell #6: Cosmodrome';
   str_camp_t[8]         := '9. ';
   str_camp_t[9]         := '10. ';
   str_camp_t[10]        := '11. ';
   str_camp_t[11]        := '12. ';
   str_camp_t[12]        := '13. ';
   str_camp_t[13]        := '14. ';
   str_camp_t[14]        := '15. ';
   str_camp_t[15]        := '16. ';
   str_camp_t[16]        := '17. ';
   str_camp_t[17]        := '18. ';
   str_camp_t[18]        := '19. ';
   str_camp_t[19]        := '20. ';
   str_camp_t[20]        := '21. ';
   str_camp_t[21]        := '22. ';

   str_camp_o[0]         := '-Destroy all human bases and armies'+#13+'-Protect the Portal';
   str_camp_o[1]         := '-Destroy Military Base';
   str_camp_o[2]         := '-Destroy all human bases and armies'+#13+'-Protect the Portal';
   str_camp_o[3]         := '-Protect the altars for 20 minutes';
   str_camp_o[4]         := '-Destroy all human bases and armies';
   str_camp_o[5]         := '-Destroy all human bases and armies';
   str_camp_o[6]         := '-Destroy all human bases and armies';
   str_camp_o[7]         := '-Destroy Cosmodrome'+#13+'-No human transport should escape';

   str_camp_m[0]         := #18+'Date:'+#25+#12+'15.11.2145'+#12+#18+'Location:'+#25+#12+'PHOBOS'+#12+#18+'Area:'+#25+#12+'Anomaly Zone';
   str_camp_m[1]         := #18+'Date:'+#25+#12+'16.11.2145'+#12+#18+'Location:'+#25+#12+'PHOBOS'+#12+#18+'Area:'+#25+#12+'Hall crater';
   str_camp_m[2]         := #18+'Date:'+#25+#12+'15.11.2145'+#12+#18+'Location:'+#25+#12+'DEIMOS'+#12+#18+'Area:'+#25+#12+'Anomaly Zone';
   str_camp_m[3]         := #18+'Date:'+#25+#12+'16.11.2145'+#12+#18+'Location:'+#25+#12+'DEIMOS'+#12+#18+'Area:'+#25+#12+'Swift crater';
   str_camp_m[4]         := #18+'Date:'+#25+#12+'18.11.2145'+#12+#18+'Location:'+#25+#12+'MARS'  +#12+#18+'Area:'+#25+#12+'Hellas Area';
   str_camp_m[5]         := #18+'Date:'+#25+#12+'19.11.2145'+#12+#18+'Location:'+#25+#12+'MARS'  +#12+#18+'Area:'+#25+#12+'Hellas Area';
   str_camp_m[6]         := #18+'Date:'+#25+#12+'18.11.2145'+#12+#18+'Location:'+#25+#12+'EARTH' +#12+#18+'Area:'+#25+#12+'Unknown';
   str_camp_m[7]         := #18+'Date:'+#25+#12+'19.11.2145'+#12+#18+'Location:'+#25+#12+'EARTH' +#12+#18+'Area:'+#25+#12+'Unknown';

   {
   str_cmp_mn[1 ] := 'Hell #1: Invasion on Phobos';
   str_cmp_mn[2 ] := 'Hell #2: Toxin Refinery';
   str_cmp_mn[3 ] := 'Hell #3: Military Base';
   str_cmp_mn[4 ] := 'Hell #4: Deimos Anomaly';
   str_cmp_mn[5 ] := 'Hell #5: Nuclear Plant';
   str_cmp_mn[6 ] := 'Hell #6: Science Center';
   str_cmp_mn[7 ] := 'Hell #7: Quarry';
   str_cmp_mn[8 ] := 'Hell #8: Hell on Mars';
   str_cmp_mn[9 ] := 'Hell #9: Hell On Earth';
   str_cmp_mn[10] := 'Hell #10: Industrial Zone';
   str_cmp_mn[11] := 'Hell #11: Cosmodrome';
   str_cmp_mn[12] := 'UAC #1: Command Center';
   str_cmp_mn[13] := 'UAC #2: Super Generators';
   str_cmp_mn[14] := 'UAC #3: Phobos Anomaly';
   str_cmp_mn[15] := 'UAC #4: Deimos Anomaly 2';
   str_cmp_mn[16] := 'UAC #5: Lab';
   str_cmp_mn[17] := 'UAC #6: Fortress of Mystery';
   str_cmp_mn[18] := 'UAC #7: City of the Damned';
   str_cmp_mn[19] := 'UAC #8: Slough of Despair';
   str_cmp_mn[20] := 'UAC #9: Mt. Erebus';
   str_cmp_mn[21] := 'UAC #10: Dead Zone';
   str_cmp_mn[22] := 'UAC #11: Battle For Mars';

   str_cmp_ob[1 ] := '-Destroy all human bases and armies'+#13+'-Protect portal';
   str_cmp_ob[2 ] := '-Destroy Toxin Refinery';
   str_cmp_ob[3 ] := '-Destroy Military Base';
   str_cmp_ob[4 ] := '-Destroy all human bases and armies'+#13+'-Cyberdemon must survive'+#13+'-Protect portal';
   str_cmp_ob[5 ] := '-Destroy Nuclear Plant'+#13+'-Cyberdemon must survive';
   str_cmp_ob[6 ] := '-Destroy Science Center'+#13+'-Cyberdemon must survive';
   str_cmp_ob[7 ] := '-Destroy all human bases and armies';
   str_cmp_ob[8 ] := '-Kill all humans!';
   str_cmp_ob[9 ] := '-Protect Hell Fortess'+#13+'-Destroy all human towns and armies';
   str_cmp_ob[10] := '-Destroy all industrial buildings'+#13+'-Destroy all command centers';
   str_cmp_ob[11] := '-Destroy all military bases';
   str_cmp_ob[12] := '-Find, protect and reapir'+#13+'Command Center'+#13+'-At least one engineer must survive';
   str_cmp_ob[13] := '-Find and repair 5 Super Generators';
   str_cmp_ob[14] := '-Destroy all bases and armies of hell'+#13+'around portal until the arrival of'+#13+'enemy reinforcements(for 20 minutes)';
   str_cmp_ob[15] := '-Destroy all bases and armies of hell'+#13+'-Protect portal';
   str_cmp_ob[16] := '-Repair and protect Science Center'+#13+'-Destroy all bases and armies of hell';
   str_cmp_ob[17] := '-Destroy fortess of hell';
   str_cmp_ob[18] := '-Destroy all altars of hell'+#13+'-Protect portal';
   str_cmp_ob[19] := '-Reach the opposite side of the area';
   str_cmp_ob[20] := '-Find and kill the Spiderdemon';
   str_cmp_ob[21] := '-Cleanse the Quarry';
   str_cmp_ob[22] := '-Destroy all bases and armies of hell';

   str_cmp_map[1 ] := 'Date:'+#12+'15.11.2145'+#12+'Location:'+#12+'PHOBOS'+#12+'Area:'+#12+'Anomaly Zone';
   str_cmp_map[2 ] := 'Date:'+#12+'15.11.2145'+#12+'Location:'+#12+'PHOBOS'+#12+'Area:'+#12+'Hall crater';
   str_cmp_map[3 ] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'PHOBOS'+#12+'Area:'+#12+'Drunlo crater';
   str_cmp_map[4 ] := 'Date:'+#12+'15.11.2145'+#12+'Location:'+#12+'DEIMOS'+#12+'Area:'+#12+'Anomaly Zone';
   str_cmp_map[5 ] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'DEIMOS'+#12+'Area:'+#12+'Swift crater';
   str_cmp_map[6 ] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'DEIMOS'+#12+'Area:'+#12+'Voltaire Area';
   str_cmp_map[7 ] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'MARS'  +#12+'Area:'+#12+'Hellas Area';
   str_cmp_map[8 ] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'MARS'  +#12+'Area:'+#12+'Hellas Area';
   str_cmp_map[9 ] := 'Date:'+#12+'25.11.2145'+#12+'Location:'+#12+'EARTH' +#12+'Area:'+#12+'Unknown';
   str_cmp_map[10] := 'Date:'+#12+'26.11.2145'+#12+'Location:'+#12+'EARTH' +#12+'Area:'+#12+'Unknown';
   str_cmp_map[11] := 'Date:'+#12+'27.11.2145'+#12+'Location:'+#12+'EARTH' +#12+'Area:'+#12+'Unknown';
   str_cmp_map[12] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'PHOBOS'+#12+'Area:'+#12+'Todd crater';
   str_cmp_map[13] := 'Date:'+#12+'16.11.2145'+#12+'Location:'+#12+'PHOBOS'+#12+'Area:'+#12+'Roche crater';
   str_cmp_map[14] := 'Date:'+#12+'17.11.2145'+#12+'Location:'+#12+'PHOBOS'+#12+'Area:'+#12+'Anomaly Zone';
   str_cmp_map[15] := 'Date:'+#12+'17.11.2145'+#12+'Location:'+#12+'DEIMOS'+#12+'Area:'+#12+'Anomaly Zone';
   str_cmp_map[16] := 'Date:'+#12+'18.11.2145'+#12+'Location:'+#12+'DEIMOS'+#12+'Area:'+#12+'Voltaire Area';
   str_cmp_map[17] := 'Date:'+#12+'18.11.2145'+#12+'Location:'+#12+'DEIMOS'+#12+'Area:'+#12+'Voltaire Area';
   str_cmp_map[18] := 'Date:'+#12+'20.11.2145'+#12+'Location:'+#12+'HELL'  +#12+'Area:'+#12+'Unknown';
   str_cmp_map[19] := 'Date:'+#12+'21.11.2145'+#12+'Location:'+#12+'HELL'  +#12+'Area:'+#12+'Unknown';
   str_cmp_map[20] := 'Date:'+#12+'22.11.2145'+#12+'Location:'+#12+'HELL'  +#12+'Area:'+#12+'Unknown';
   str_cmp_map[21] := 'Date:'+#12+'21.11.2145'+#12+'Location:'+#12+'MARS'  +#12+'Area:'+#12+'Hellas Area';
   str_cmp_map[22] := 'Date:'+#12+'22.11.2145'+#12+'Location:'+#12+'MARS'  +#12+'Area:'+#12+'Hellas Area';

   }
end;

procedure lng_rus;
begin
  str_MMap              := 'КАРТА';
  str_MPlayers          := 'ИГРОКИ';
  str_MObjectives       := 'ЗАДАЧИ';
  str_menu_s1[ms1_sett] := 'НАСТРОЙКИ';
  str_menu_s1[ms1_svld] := 'СОХР./ЗАГР.';
  str_menu_s1[ms1_reps] := 'ЗАПИСИ';
  str_menu_s2[ms2_camp] := 'КАМПАНИИ';
  str_menu_s2[ms2_scir] := 'СХВАТКА';
  str_menu_s2[ms2_mult] := 'СЕТЕВАЯ ИГРА';
  str_reset[false]      := 'НАЧАТЬ';
  str_reset[true ]      := 'СБРОС';
  str_exit[false]       := 'ВЫХОД';
  str_exit[true]        := 'НАЗАД';
  str_m_liq             := 'Озера: ';
  str_m_siz             := 'Размер: ';
  str_m_obs             := 'Преграды: x';
  str_map               := 'Карта';
  str_players           := 'Игроки';
  str_mrandom           := 'Случайная карта';
  str_sound             := 'ГРОМКОСТЬ ЗВУКА';
  str_musicvol          := 'Музыка';
  str_soundvol          := 'Звуки';
  str_game              := 'ИГРА';
  str_scrollspd         := 'Скорость пр.';
  str_mousescrl         := 'Прокр. мышью:';
  str_fullscreen        := 'В окне:';
  str_plname            := 'Имя игрока';
  str_maction           := 'Правый клик';
  str_maction2[true ]   := #18+'Движение'+#25;
  str_maction2[false]   := #17+'Движение'+#25+'+'+#17+'атака'+#25;
  str_race[r_random]    := 'случ.';
  str_pause             := 'Пауза';
  str_win               := 'ПОБЕДА!';
  str_lose              := 'ПОРАЖЕНИЕ!';
  str_gsaved            := 'Игра сохранена';
  str_repend            := 'Конец записи!';
  str_save              := 'Сохранить';
  str_load              := 'Загрузить';
  str_delete            := 'Удалить';
  str_svld_errors[1]    := 'Файл не'+#13+'существует!';
  str_svld_errors[2]    := 'Невозможно'+#13+'открыть файл!';
  str_svld_errors[3]    := 'Неправильный'+#13+'размер файла!';
  str_svld_errors[4]    := 'Неправильная'+#13+'версия файла!';
  str_time              := 'Время: ';
  str_menu              := 'Меню';
  str_player_def        := ' уничтожен!';
  str_inv_time          := 'Волна #';
  str_inv_ml            := 'Монстры: ';
  str_play              := 'Проиграть';
  str_replay            := 'ЗАПИСЬ';
  str_cmpdif            := 'Сложность: ';
  str_waitsv            := 'Ожидание сервера...';
  str_goptions          := 'ПАРАМЕТРЫ ИГРЫ';
  str_server            := 'СЕРВЕР';
  str_client            := 'КЛИЕНТ';
  str_chat              := 'ЧАТ';
  str_gaddon            := 'Игра:';
  str_randoms           := 'Случайная схватка';
  str_apply             := 'применить';
  str_plout             := ' покинул игру';

  str_loss              := 'Условие поражения:';
  str_losst[0]          := 'нет армии';
  str_losst[1]          := 'нет строителей';
  str_losst[2]          := 'нет энергии';

  str_starta            := 'Начальная база:';
  str_startat[0]        := '1 '+#19+'строитель'+#25;
  str_startat[1]        := '1 '+#19+'строитель'+#25+'+ 1 '+#18+'ген.'+#25;
  str_startat[2]        := '1 '+#19+'строитель'+#25+'+ 2 '+#18+'ген.'+#25;
  str_startat[3]        := '1 '+#19+'стр.'+#25+'+ 2 '+#18+'ген.'+#25+'+ 2 '+#17+'б.'+#25;

  str_onebase           := 'Один строитель:';

  str_pnua[0]           := #19+'наименьш.'+#25+'/'+#15+'наихудш.'+#25;
  str_pnua[1]           := #18+' маленький'+#25+'/'+#16+'плохое'+#25;
  str_pnua[2]           := #17+' средний'+#25+'/'+#17+'среднее'+#25;
  str_pnua[3]           := #16+' большой'+#25+'/'+#18+'хорошее'+#25;
  str_pnua[4]           := #15+' наибольший'+#25+'/'+#19+'лучшее'+#25;

  str_npnua[0]          := #15+'очень редко'+#25;
  str_npnua[1]          := #16+'редко'      +#25;
  str_npnua[2]          := #17+'умеренно'   +#25;
  str_npnua[3]          := #18+'часто'      +#25;
  str_npnua[4]          := #19+'очень часто'+#25;

  str_gmodet            := 'Режим игры:';
  str_gmode[0]          := 'Схватка';
  str_gmode[1]          := 'Две крепости';
  str_gmode[2]          := 'Захват точек';
  str_gmode[3]          := 'Вторжение';
  str_gmode[4]          := 'Штурм';

  str_team              := 'Клан:';
  str_srace             := 'Раса:';
  str_ready             := 'Готов: ';
  str_udpport           := 'UDP порт:';
  str_svup[false]       := 'Вкл. сервер';
  str_svup[true ]       := 'Выкл. сервер';
  str_connect[false]    := 'Подключится';
  str_connect[true ]    := 'Откл.';
  str_pnu               := 'Размер/качество:';
  str_npnu              := 'Обновление юнитов: ';
  str_connecting        := 'Соединение...';
  str_sver              := 'Другая версия!';
  str_sfull             := 'Нет мест!';
  str_sgst              := 'Игра началась!';

  str_hint_t[0]         := 'Здания и юниты';
  str_hint_t[1]         := 'Исследования';
  str_hint_t[2]         := 'Запись';

  str_hint_m[0]         := 'Меню ('          +#18+'Esc'+#25+')';
  str_hint_m[2]         := 'Пауза ('         +#18+'Pause/Break'+#25+')';

  with _ulst[UID_HKeep     ] do str_hint[0,r_hell,0 ] := 'Адская крепость (' +#18+'Q'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Строит базу.';
  with _ulst[UID_HGate     ] do str_hint[0,r_hell,1 ] := 'Адские врата ('    +#18+'W'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Призывает армию.';
  with _ulst[UID_HSymbol   ] do str_hint[0,r_hell,2 ] := 'Адский символ ('   +#18+'E'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Добавляет энергию.';
  with _ulst[UID_HPools    ] do str_hint[0,r_hell,3 ] := 'Адский омут ('     +#18+'A'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Исследует улучшения.';
  with _ulst[UID_HTower    ] do str_hint[0,r_hell,4 ] := 'Адская башня ('    +#18+'S'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Защитное сооружение.';
  with _ulst[UID_HTeleport ] do str_hint[0,r_hell,5 ] := 'Адский телепорт (' +#18+'D'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Перемещает юнитов в любую точку карты.';
  with _ulst[UID_HMonastery] do str_hint[0,r_hell,6 ] := 'Адский монастырь ('+#18+'Z'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Улучшает юнитов. '+#11+#17+'Требования:'+#25+' Адский омут';
  with _ulst[UID_HTotem    ] do str_hint[0,r_hell,7 ] := 'Адский тотем ('    +#18+'X'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Продвинутое защитное сооружение. '+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  with _ulst[UID_HAltar    ] do str_hint[0,r_hell,8 ] := 'Адский алтарь ('   +#18+'C'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Восстанавливает здания и накладывает на юнитов эффект "адская сила".'+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[0,r_hell,9 ] := 'Lost Soul ('     +#18+'R'+#25+') ['+#19+b2s(_ulst[UID_LostSoul   ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,10] := 'Imp ('           +#18+'T'+#25+') ['+#19+b2s(_ulst[UID_Imp        ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,11] := 'Demon ('         +#18+'Y'+#25+') ['+#19+b2s(_ulst[UID_Demon      ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,12] := 'Cacodemon ('     +#18+'F'+#25+') ['+#19+b2s(_ulst[UID_Cacodemon  ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,13] := 'Baron of Hell / Hell Knight ('
                                             +#18+'G'+#25+') ['+#19+b2s(_ulst[UID_Baron      ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,14] := 'Cyberdemon ('    +#18+'H'+#25+') ['+#19+b2s(_ulst[UID_Cyberdemon ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,15] := 'Mastermind ('    +#18+'V'+#25+') ['+#19+b2s(_ulst[UID_Mastermind ].trt div vid_fps)+#25+']';
  str_hint[0,r_hell,16] := 'Pain Elemental ('+#18+'B'+#25+') ['+#19+b2s(_ulst[UID_Pain       ].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[0,r_hell,17] := 'Revenant ('      +#18+'N'+#25+') ['+#19+b2s(_ulst[UID_Revenant   ].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[0,r_hell,18] := 'Mancubus ('      +#18+'U'+#25+') ['+#19+b2s(_ulst[UID_Mancubus   ].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[0,r_hell,19] := 'Arachnotron ('   +#18+'I'+#25+') ['+#19+b2s(_ulst[UID_Arachnotron].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[0,r_hell,20] := 'ArchVile ('      +#18+'O'+#25+') ['+#19+b2s(_ulst[UID_ArchVile   ].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';

  str_hint[1,r_hell,upgr_attack ] := 'Улучшение дальней атаки ('       +#18+'Q'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_attack  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_attack ])+#25+#11+'Увеличение урона дальней атаки.';
  str_hint[1,r_hell,upgr_armor  ] := 'Улучшение защиты юнитов ('       +#18+'W'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_armor   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_armor  ])+#25+#11+'Увеличение защиты юнитов.';
  str_hint[1,r_hell,upgr_build  ] := 'Улучшение защиты зданий ('       +#18+'E'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_build   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_build  ])+#25+#11+'Увеличение защиты зданий.';
  str_hint[1,r_hell,upgr_melee  ] := 'Улучшение ближней атаки ('       +#18+'A'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_melee   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_melee  ])+#25+#11+'Увеличение урона ближней атаки.';
  str_hint[1,r_hell,upgr_regen  ] := 'Регенерация ('                   +#18+'S'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_regen   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_regen  ])+#25+#11+'Юниты медленно восстанавливают свое здоровье.';
  str_hint[1,r_hell,upgr_paina  ] := 'Аура разрушения ('               +#18+'D'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_paina   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_paina  ])+#25+#11+'Адская крепость наносит урон всем врагам вокруг.';
  str_hint[1,r_hell,upgr_vision ] := 'Адское зрение ('                 +#18+'Z'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_vision  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_vision ])+#25+#11+'Cyberdemon, Mastermind и адский альтарь становятся детекторами.';
  str_hint[1,r_hell,upgr_pains  ] := 'Болевой порог ('                 +#18+'X'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_pains   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_pains  ])+#25+#11+'Уменьшает шанс "pain state".';
  str_hint[1,r_hell,upgr_5bld   ] := 'Улучшение телепорта ('           +#18+'C'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_5bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_5bld   ])+#25+#11+'Уменьшает время перезарядки телепорта.';
  str_hint[1,r_hell,upgr_mainm  ] := 'Телепортация адской крепости ('  +#18+'R'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_mainm   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_mainm  ])+#25+#11+'Адская крепость может перемещаться в любую свободную точку карты.';
  str_hint[1,r_hell,upgr_towers ] := 'Увеличение радиуса атаки защитных сооружений ('   +#18+'T'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_towers  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_towers ]);
  str_hint[1,r_hell,upgr_6bld   ] := 'Сборщик душ ('                   +#18+'Y'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_6bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_6bld   ])+#25+#11+'Адский монастырь может улучшать юнитов.';
  str_hint[1,r_hell,upgr_2tier  ] := 'Древнее зло ('                   +#18+'F'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_2tier   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_2tier  ])+#25+#11+'Второй уровень зданий, юнитов и улучшений.';
  str_hint[1,r_hell,upgr_mainr  ] := 'Увеличение радиуса зрения адской крепости ('      +#18+'G'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_mainr   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_mainr  ])+#25+#11+'Увеличивает радиус зрения адской крепости.'            +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_revtele] := 'Обратный телепорт ('             +#18+'H'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_revtele ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_revtele ])+#25+#11+'Юниты могу перемещаться в адский телепорт.'                            +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_revmis ] := 'Улучшение атаки юнита Revenant ('+#18+'V'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_revmis  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_revmis  ])+#25+#11+'Увеличение дистанции атаки, снаряды становяться самонаводящимися.'     +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_hpower ] := 'Адская сила ('                   +#18+'N'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_hpower  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_hpower  ])+#25+#11+'Улучшение способности Адского алтаря.'                                 +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_hsymbol] := 'Улучшение Адского Символа ('     +#18+'B'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_hsymbol ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_hsymbol ])+#25+#11+'+1 к энергии для каждого адского символа.'                             +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_bldrep ] := 'Восстановление зданий ('         +#18+'U'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_bldrep  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_bldrep  ])+#25+#11+'Способность Адского алтаря.'                                           +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_6bld2  ] := 'Хранилище душ ('                 +#18+'I'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_6bld2   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_6bld2   ])+#25+#11+'Адский монастырь может хранить больше душ.'                            +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_mainonr] := 'Свободная телепортация ('        +#18+'O'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_mainonr ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_mainonr ])+#25+#11+'Адская крепость может перемещаться на скалы, озера и др. препятствия.' +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_b478tel] := 'Телепортация символов, башен и алтарей ('  +#18+'J'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_b478tel ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_b478tel ])+#25+#11+'АДские символы, башни, тотемы и алтари могут телепортироваться на короткое расстояние.'+#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';
  str_hint[1,r_hell,upgr_hinvuln] := 'Временная неуязвимость ('        +#18+'K'+#25+') ['+#19+i2s(upgrade_time[r_hell,upgr_hinvuln ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_hell,upgr_hinvuln ])+#25+#11+'Все юниты становятся неуязвимыми на 15 секунд.'                        +#11+#17+'Требования:'+#25+' Адский монастырь, исследование "Древнее зло".';

  with _ulst[UID_UCommandCenter ] do str_hint[0,r_uac ,0 ] := 'Командный центр ('        +#18+'Q'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Строит базу.';
  with _ulst[UID_UMilitaryUnit  ] do str_hint[0,r_uac ,1 ] := 'Войсковая часть ('        +#18+'W'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Тренирует юнитов.';
  with _ulst[UID_UGenerator     ] do str_hint[0,r_uac ,2 ] := 'Генератор ('              +#18+'E'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Добавляет энергию.';
  with _ulst[UID_UWeaponFactory ] do str_hint[0,r_uac ,3 ] := 'Завод вооружений ('       +#18+'A'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Исследует улучшения.';
  with _ulst[UID_UTurret        ] do str_hint[0,r_uac ,4 ] := 'Турель ('                 +#18+'S'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Защитное сооружение.';
  with _ulst[UID_URadar         ] do str_hint[0,r_uac ,5 ] := 'Радар ('                  +#18+'D'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Раскрывает карту.';
  with _ulst[UID_UVehicleFactory] do str_hint[0,r_uac ,6 ] := 'Технический центр ('      +#18+'Z'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Улучшает юнитов. '                +#11+#17+'Требования:'+#25+' Завод вооружений';
  with _ulst[UID_URTurret       ] do str_hint[0,r_uac ,7 ] := 'Ракетная турель ('        +#18+'X'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Продвинутое защитное сооружение. '+#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  with _ulst[UID_URocketL       ] do str_hint[0,r_uac ,8 ] := 'Станция ракетного залпа ('+#18+'C'+#25+') ['+#19+i2s(mhits div bld_s div 2)+#25+']'+#11+'Производит ракетный удар. Для залпа требуется исследование "Ракетный удар".'        +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[0,r_uac ,9 ] := 'Инженер ('            +#18+'R'+#25+') ['+#19+b2s(_ulst[UID_Engineer  ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,10] := 'Медик ('              +#18+'T'+#25+') ['+#19+b2s(_ulst[UID_Medic     ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,11] := 'Сержант ('            +#18+'Y'+#25+') ['+#19+b2s(_ulst[UID_Sergant   ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,12] := 'Коммандо ('           +#18+'F'+#25+') ['+#19+b2s(_ulst[UID_Commando  ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,13] := 'Гранатометчик ('      +#18+'G'+#25+') ['+#19+b2s(_ulst[UID_Bomber    ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,14] := 'Майор ('              +#18+'H'+#25+') ['+#19+b2s(_ulst[UID_Major     ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,15] := 'Солдат с BFG ('       +#18+'V'+#25+') ['+#19+b2s(_ulst[UID_BFG       ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,16] := 'Воздушный транспорт ('+#18+'B'+#25+') ['+#19+b2s(_ulst[UID_FAPC      ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,17] := 'БТР ('                +#18+'N'+#25+') ['+#19+b2s(_ulst[UID_APC       ].trt div vid_fps)+#25+']';
  str_hint[0,r_uac ,18] := 'Терминатор ('         +#18+'U'+#25+') ['+#19+b2s(_ulst[UID_Terminator].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[0,r_uac ,19] := 'Танк ('               +#18+'I'+#25+') ['+#19+b2s(_ulst[UID_Tank      ].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[0,r_uac ,20] := 'Истребитель ('        +#18+'O'+#25+') ['+#19+b2s(_ulst[UID_Flyer     ].trt div vid_fps)+#25+']'+#11+#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';

  str_hint[1,r_uac ,upgr_attack ] := 'Улучшение дальней атаки ('  +#18+'Q'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_attack  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_attack ])+#25+#11+'Увеличение урона дальней атаки.';
  str_hint[1,r_uac ,upgr_armor  ] := 'Улучшение защиты пехоты ('  +#18+'W'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_armor   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_armor  ])+#25+#11+'Увеличение защиты пехоты.';
  str_hint[1,r_uac ,upgr_build  ] := 'Улучшение защиты зданий ('  +#18+'E'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_build   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_build  ])+#25+#11+'Увеличение защиты зданий.';
  str_hint[1,r_uac ,upgr_melee  ] := 'Ремонт и лечение ('         +#18+'A'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_melee   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_melee  ])+#25+#11+'Увеличение эффективности ремонта/лечения инженера/медика.';
  str_hint[1,r_uac ,upgr_mspeed ] := 'Легковесная броня ('        +#18+'S'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mspeed  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mspeed ])+#25+#11+'Увеличение скорости передвижения пехоты.';
  str_hint[1,r_uac ,upgr_shield ] := 'Плазменные щиты ('          +#18+'D'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_shield  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_shield ])+#25+#11+'Все здания и техника получают плазменные щиты.';
  str_hint[1,r_uac ,upgr_vision ] := 'Детекторы ('                +#18+'Z'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_vision  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_vision ])+#25+#11+'Радар и мины становятся детекторами.';
  str_hint[1,r_uac ,upgr_invis  ] := 'Невидимая пехота ('         +#18+'X'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_invis   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_invis  ])+#25+#11+'Пехота становится невидимой.';
  str_hint[1,r_uac ,upgr_5bld   ] := 'Улучшение радара ('         +#18+'C'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_5bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_5bld   ])+#25+#11+'Увеличиваает радиус и время разведки радара.';
  str_hint[1,r_uac ,upgr_mainm  ] := 'Полет командного центра ('  +#18+'R'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mainm   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mainm  ])+#25+#11+'Командный центр может летать.';
  str_hint[1,r_uac ,upgr_towers ] := 'Увеличение радиуса атаки защитных сооружений ('  +#18+'T'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_towers  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_towers ]);
  str_hint[1,r_uac ,upgr_6bld   ] := 'Дополнительное вооружение ('+#18+'Y'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_6bld    ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_6bld   ])+#25+#11+'Технический центр может улучшать юнитов.';
  str_hint[1,r_uac ,upgr_2tier  ] := 'Выские технологии ('        +#18+'F'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_2tier   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_2tier  ])+#25+#11+'Второй уровень зданий, юнитов и улучшений.';
  str_hint[1,r_uac ,upgr_mainr  ] := 'Увеличение радиуса зрения командного центра ('   +#18+'G'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mainr   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mainr  ])+#25+#11+'Увеличивает радиус зрения командного центра.'+#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_blizz  ] := 'Ракетный удар ('            +#18+'H'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_blizz   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_blizz  ])+#25+#11+'Ракеты для станции ракетного залпа.'                              +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_mechspd] := 'Продвинутые двигатели ('    +#18+'V'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mechspd ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mechspd])+#25+#11+'Увеличивает скорость передвижения техники.'                       +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_mecharm] := 'Улучшение защиты техники (' +#18+'B'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mecharm ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mecharm])+#25+#11+'Увеличение защиты техники.'                                       +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_ucomatt] := 'BFG турель ('               +#18+'N'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_ucomatt ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_ucomatt])+#25+#11+'Командный центр может атаковать.'                                 +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_minesen] := 'Мина-сенсор ('              +#18+'U'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_minesen ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_minesen])+#25+#11+'Способность мины.'                                                +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_6bld2  ] := 'Быстрое перевооружение ('   +#18+'I'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_6bld2   ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_6bld2  ])+#25+#11+'Технический центр быстрее улучшает юнитов.'                       +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_mainonr] := 'Свободное приземление ('    +#18+'O'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_mainonr ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_mainonr])+#25+#11+'Командный центр может приземляться на камни, озера и др. препятствия.'+#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_addtur ] := 'Дополнительная турель ('    +#18+'J'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_addtur  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_addtur ])+#25+#11+'Дополнительное оружие для турели.'                                +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';
  str_hint[1,r_uac ,upgr_apctur ] := 'Турель для транспорта ('    +#18+'K'+#25+') ['+#19+i2s(upgrade_time[r_uac ,upgr_apctur  ] div vid_fps)+#25+'] x'+#17+b2s(upgrade_cnt[r_uac ,upgr_apctur ])+#25+#11                                                                    +#11+#17+'Требования:'+#25+' Технический центр, исследование "Высокие технологии".';

  str_hint[2,r_hell,0 ] := 'Включить/выключить ускоренный просмотр ('+#18+'Q'+#25+')';
  str_hint[2,r_hell,1 ] := 'Левый клик: пропустить 2 секунды ('+#18+'W'+#25+')'+#11+'Правый клик: пропустить 10 секунд ('+#18+'Ctrl'+#25+'+'+#18+'W'+#25+')';
  str_hint[2,r_hell,2 ] := 'Список игровых сообщений ('+#18+'E'+#25+')';
  str_hint[2,r_hell,3 ] := 'Туман войны ('+#18+'A'+#25+')';
  str_hint[2,r_hell,6 ] := 'Все игроки ('+#18+'Z'+#25+')';
  str_hint[2,r_hell,7 ] := 'Красный игрок [#1] ('+#18+'X'+#25+')';
  str_hint[2,r_hell,8 ] := 'Желтый игрок [#2] ('+#18+'C'+#25+')';
  str_hint[2,r_hell,9 ] := 'Зеленый игрок [#3] ('+#18+'R'+#25+')';
  str_hint[2,r_hell,10] := 'Синий игрок [#4] ('+#18+'T'+#25+')';
  str_hint[2,r_uac ,0 ] := str_hint[2,r_hell,0 ];
  str_hint[2,r_uac ,1 ] := str_hint[2,r_hell,1 ];
  str_hint[2,r_uac ,2 ] := str_hint[2,r_hell,2 ];
  str_hint[2,r_uac ,3 ] := str_hint[2,r_hell,3 ];
  str_hint[2,r_uac ,6 ] := str_hint[2,r_hell,6 ];
  str_hint[2,r_uac ,7 ] := str_hint[2,r_hell,7 ];
  str_hint[2,r_uac ,8 ] := str_hint[2,r_hell,8 ];
  str_hint[2,r_uac ,9 ] := str_hint[2,r_hell,9 ];
  str_hint[2,r_uac ,10] := str_hint[2,r_hell,10];

  str_hint[0,r_uac ,25] := 'Мины';
  str_hint[1,r_uac ,25] := str_hint[0,r_uac ,25];
  str_hint[0,r_hell,25] := 'Зомби ('+#18+'M'+#25+')';
  str_hint[1,r_hell,25] := str_hint[0,r_hell,25];

  str_hint[0,r_hell,21] := 'Дейсвтие ('      +#18+'Ctrl'+#25+'+'+#18+'Space'+#25+')';
  str_hint[0,r_hell,22] := 'Уничтожить ('    +#18+'Delete'+#25+')';
  str_hint[0,r_hell,23] := 'Отмена ('        +#18+'Space'+#25+')';
  str_hint[1,r_hell,24] := 'Меню ('          +#18+'Esc'+#25+')';
  str_hint[0,r_uac ,21] := str_hint[0,r_hell,21];
  str_hint[0,r_uac ,22] := str_hint[0,r_hell,22];
  str_hint[0,r_uac ,23] := str_hint[0,r_hell,23];
  str_hint[0,r_uac ,24] := str_hint[0,r_hell,24];
  str_hint[1,r_uac ,24] := str_hint[1,r_hell,24];

  str_camp_t[0]         := 'Hell #1: Вторжение на Фобос';
  str_camp_t[1]         := 'Hell #2: Военная база';
  str_camp_t[2]         := 'Hell #3: Вторжение на Деймос';
  str_camp_t[3]         := 'Hell #4: Пентаграмма смерти';
  str_camp_t[4]         := 'Hell #7: Каньон';
  str_camp_t[5]         := 'Hell #8: Ад на Марсе';
  str_camp_t[6]         := 'Hell #5: Ад на Земле';
  str_camp_t[7]         := 'Hell #6: Космодром';

  str_camp_o[0]         := '-Уничтожь все людские базы и армии'+#13+'-Защити портал';
  str_camp_o[1]         := '-Уничтожь военную базу';
  str_camp_o[2]         := '-Уничтожь все людские базы и армии'+#13+'-Защити портал';
  str_camp_o[3]         := '-Защити алтари в течении 20 минут';
  str_camp_o[4]         := '-Уничтожь все людские базы и армии';
  str_camp_o[5]         := '-Уничтожь все людские базы и армии';
  str_camp_o[6]         := '-Уничтожь все людские базы и армии';
  str_camp_o[7]         := '-Уничтожь космодром'+#13+'-Ни один людской транспорт не должен'+#13+'уйти';

  str_camp_m[0]         := #18+'Дата:'+#25+#12+'15.11.2145'+#12+#18+'Место:'+#25+#12+'ФОБОС' +#12+#18+'Район:'+#25+#12+'Аномалия';
  str_camp_m[1]         := #18+'Дата:'+#25+#12+'16.11.2145'+#12+#18+'Место:'+#25+#12+'ФОБОС' +#12+#18+'Район:'+#25+#12+'Кратер Халл';
  str_camp_m[2]         := #18+'Дата:'+#25+#12+'15.11.2145'+#12+#18+'Место:'+#25+#12+'ДЕЙМОС'+#12+#18+'Район:'+#25+#12+'Аномалия';
  str_camp_m[3]         := #18+'Дата:'+#25+#12+'16.11.2145'+#12+#18+'Место:'+#25+#12+'ДЕЙМОС'+#12+#18+'Район:'+#25+#12+'Кратер Свифт';
  str_camp_m[4]         := #18+'Дата:'+#25+#12+'18.11.2145'+#12+#18+'Место:'+#25+#12+'МАРС'  +#12+#18+'Район:'+#25+#12+'Равнина Хеллас';
  str_camp_m[5]         := #18+'Дата:'+#25+#12+'19.11.2145'+#12+#18+'Место:'+#25+#12+'МАРС'  +#12+#18+'Район:'+#25+#12+'Равнина Хеллас';
  str_camp_m[6]         := #18+'Дата:'+#25+#12+'18.11.2145'+#12+#18+'Место:'+#25+#12+'ЗЕМЛЯ' +#12+#18+'Район:'+#25+#12+'Неизвестно';
  str_camp_m[7]         := #18+'Дата:'+#25+#12+'19.11.2145'+#12+#18+'Место:'+#25+#12+'ЗЕМЛЯ' +#12+#18+'Район:'+#25+#12+'Неизвестно';
end;


procedure swLNG;
begin
  if(_lng)
  then lng_rus
  else lng_eng;
end;



